# Generated by Django 5.1.7 on 2025-04-03 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='std_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='CGPA',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(default='Undeclared', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_certificate',
            field=models.FileField(default='certificates/default_certificate.pdf', upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(default='default_student_id', max_length=20, unique=True),
        ),
    ]
