# Generated by Django 5.1.7 on 2025-04-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_studentprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni')], default='Student', max_length=10),
        ),
    ]
