# Generated by Django 5.1.7 on 2025-04-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studentprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='awards',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='company',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github',
            field=models.URLField(blank=True, default='https://github.com', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='industry',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='job_title',
            field=models.CharField(blank=True, default='Unemployed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='offering_referrals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='open_to_mentorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tagline',
            field=models.CharField(blank=True, default='No tagline provided', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='website',
            field=models.URLField(blank=True, default='https://example.com', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
