# Generated by Django 5.1.7 on 2025-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_studentprofile_awards_studentprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='university_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
