# Generated by Django 5.1.7 on 2025-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_studentprofile_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='awards',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='projects',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
