# Generated by Django 5.1.7 on 2025-04-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
