# Generated by Django 5.1.7 on 2025-04-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_studentprofile_student_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_approved',
            new_name='approved',
        ),
    ]
