# Generated by Django 5.1.7 on 2025-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_student_approved_studentprofile_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(default=2000, null=True),
        ),
    ]
