# Generated by Django 5.1.7 on 2025-04-18 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_studentprofile_graduation_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
