# Generated by Django 5.1.7 on 2025-05-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_mentorshippost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
